services:
  mariadb:
    build:
        context: requirements/mariadb
    container_name: mariadb
    image: mariadb:mariadb
    pull_policy: never
    ports:
      - 3306:3306
    networks:
      - inception

  nginx:
    build:
        context: requirements/nginx
    container_name: nginx
    image: nginx:nginx
    pull_policy: never
    ports:
      #- 443:443
      - 80:8080
    networks:
      - inception

  wordpress:
    build:
        context: requirements/wordpress
    container_name: wordpress
    image: wordpress:wordpress
    pull_policy: never
    ports:
      - 9000:9000
    networks:
      - inception

networks:
  inception:
    name: inception
