services:
  mariadb:
    hostname: mariadb
    build:
        context: requirements/mariadb
        args:
          DB_PATH: ${DB_PATH}
          DB_NAME: ${DB_NAME}
          DB_USER: ${DB_USER}
          WP_PASSWORD: ${WP_PASSWORD}
          DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    container_name: mariadb
    image: mariadb:mariadb
    pull_policy: never
    env_file:
      - .env
    networks:
      - inception

  nginx:
    build:
        context: requirements/nginx
    container_name: nginx
    image: nginx:nginx
    pull_policy: never
    env_file:
      - .env
    ports:
      - 443:443
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception

  wordpress:
    hostname: wordpress
    build:
        context: requirements/wordpress
        args:
          DB_NAME: ${DB_NAME}
          DB_USER: ${DB_USER}
          WP_PASSWORD: ${WP_PASSWORD}
          DB_HOST: ${DB_HOST}
    container_name: wordpress
    image: wordpress:wordpress
    pull_policy: never
    env_file:
      - .env
    #ports:
    #  - 9000:9000
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception

networks:
  inception:
    name: inception
