services:
  mariadb:
    hostname: mariadb
    build:
        context: requirements/mariadb
        args:
          DB_PATH: ${DB_PATH}
          DB_NAME: ${DB_NAME}
          DB_USER: ${DB_USER}
          WP_PASSWORD: ${WP_PASSWORD}
          DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    container_name: mariadb
    image: mariadb:mariadb
    pull_policy: never
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
      #- /home/${LOGIN}/data/mariadb:/var/lib/mysql
    networks:
      - inception

  nginx:
    build:
        context: requirements/nginx
        args:
          DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    image: nginx:nginx
    pull_policy: never
    env_file:
      - .env
    ports:
      - 443:443
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
      # - /home/${LOGIN}/data/wordpress:/var/www/wordpress
    networks:
      - inception

  wordpress:
    hostname: wordpress
    build:
        context: requirements/wordpress
        args:
          DB_NAME: ${DB_NAME}
          DB_USER: ${DB_USER}
          WP_PASSWORD: ${WP_PASSWORD}
          DB_HOST: ${DB_HOST}
    container_name: wordpress
    image: wordpress:wordpress
    pull_policy: never
    env_file:
      - .env
    #ports:
    #  - 9000:9000
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
      #- /home/${LOGIN}/data/wordpress:/var/www/wordpress
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress

 # mariadb_vol:
  #  name: mariadb_vol
#    driver: local

#volumes:
#  mariadb_vol:
#    name: mariadb_vol
#    driver: local
#    driver_opts:
#      device: /home/${LOGIN}/data/mariadb
#      o : bind
#      type : none
#  wordpress_vol:
#    name: wordpress_vol
#    driver: local
#    driver_opts:
#      device: /home/${LOGIN}/data/wordpress
#      o : bind
#      type : none

networks:
  inception:
    name: inception
