services:
  mariadb:
    build:
        context: requirements/mariadb
    container_name: mariadb
    image: mariadb
    pull_policy: never
    ports:
      - 3306:3306
#   volumes:
#     - "mariadb-data:/var/lib/mysql"

  nginx:
    build:
        context: requirements/nginx
    container_name: nginx
    image: nginx
    pull_policy: never
    ports:
      - 443:443

networks:
  inception:
    name: inception
