services:
  mariadb:
    build:
        context: requirements/mariadb
    container_name: mariadb
    image: mariadb
    pull_policy: never
    ports:
      - 3306:3306
    networks:
      - inception
#   volumes:
#     - "mariadb-data:/var/lib/mysql"

  nginx:
    build:
        context: requirements/nginx
    container_name: nginx
    image: nginx
    pull_policy: never
    ports:
      #- 443:443
      - 80:8080
    networks:
      - inception

networks:
  inception:
    name: inception
